site: isaacboor.me
title: isaacboor.me
greetings: Hi! I'm Isaac
description: >-
  Casual programmer and video editor
lang: en-GB
timezone: Europe/London
data-theme: dark # default theme "dark" | "light"

author:
  name: gesko
  bio: just a minimalist, personal blog
  userpicture:
  username: # general username
  github: # github username
  twitter: # twitter username
  email: your-email@email.com # email adress

# Font Settings
googlewebfonts: family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700

# URL settings
url: "" # Domain Name of host. [username].github.io for github pages # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
